import './globals.css';
import './_normalize.scss';
import type { Metadata } from 'next';
import React from 'react';
import Header from '@/components/header/Header';
import {raleWay} from '@/app/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
    <Header/>
    <main className={raleWay.className}>{children}</main>
    </body>
    </html>
  )
}
